[package]
name = "protocol"
version = "0.0.1"
edition = "2018"
authors = ["Andrey Zheleznov <zheland.net@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]
